// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQdnpws9CjZeIV1bDEKy_tx1ctPFC1vDU',
    appId: '1:985909607936:web:929ac5695287e1dc7762e5',
    messagingSenderId: '985909607936',
    projectId: 'paramadenah-708b7',
    authDomain: 'paramadenah-708b7.firebaseapp.com',
    databaseURL: 'https://paramadenah-708b7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'paramadenah-708b7.firebasestorage.app',
    measurementId: 'G-8DRW3B60DH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxVBdgit0XQnUzN4TEymPKjvmqhaMzyyQ',
    appId: '1:985909607936:android:bcbd414af1e782eb7762e5',
    messagingSenderId: '985909607936',
    projectId: 'paramadenah-708b7',
    databaseURL: 'https://paramadenah-708b7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'paramadenah-708b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAjr3AX0UYqN_Zyot9TC0DTLwTQpNRLXI',
    appId: '1:985909607936:ios:c67c89ead155fbc17762e5',
    messagingSenderId: '985909607936',
    projectId: 'paramadenah-708b7',
    databaseURL: 'https://paramadenah-708b7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'paramadenah-708b7.firebasestorage.app',
    iosClientId: '985909607936-monam64sjlr1lbrh6vboib5qr92jrrot.apps.googleusercontent.com',
    iosBundleId: 'com.example.paramadenahUpdate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQdnpws9CjZeIV1bDEKy_tx1ctPFC1vDU',
    appId: '1:985909607936:web:701625f3d5aa3cb37762e5',
    messagingSenderId: '985909607936',
    projectId: 'paramadenah-708b7',
    authDomain: 'paramadenah-708b7.firebaseapp.com',
    databaseURL: 'https://paramadenah-708b7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'paramadenah-708b7.firebasestorage.app',
    measurementId: 'G-7DM8RQ0ZTP',
  );
}
